version: "3"
services:
  card-properties-db:
    image: postgres:12.1-alpine
    deploy:
      replicas: 1
    restart: always
    port: "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
